"""The shared CRUD contract every lookup resource must honour.

These six resources are generated by `crud_router`, so the point of
parametrising is to prove they cannot drift apart again.
"""

import pytest

# path, create payload, patch payload, whether a duplicate must be rejected.
# Academy.name is indexed but not unique, so duplicates are legal there.
LOOKUPS = [
    ("/portfolio/tags", {"name": "Rust"}, {"name": "Rust 2"}, True),
    ("/portfolio/academies", {"name": "Coursera"}, {"name": "Coursera Plus"}, False),
    ("/portfolio/categories", {"name": "Backend"}, {"name": "Backend Eng"}, True),
    ("/portfolio/project-types", {"name": "Web"}, {"name": "Web App"}, True),
    ("/portfolio/difficulty-levels", {"name": "Hard"}, {"name": "Very Hard"}, True),
    ("/portfolio/languages", {"code": "en", "name": "English"}, {"name": "British"}, True),
]
LOOKUP_IDS = [path.rsplit("/", 1)[-1] for path, *_ in LOOKUPS]

ALL = pytest.mark.parametrize(("path", "payload", "patch", "unique"), LOOKUPS, ids=LOOKUP_IDS)


def identifier(body: dict):
    """Languages are keyed by `code`, everything else by `id`."""
    return body.get("id", body.get("code"))


@ALL
def test_full_lifecycle(client, auth, path, payload, patch, unique):
    created = client.post(path, json=payload, headers=auth)
    assert created.status_code == 201
    ident = identifier(created.json())

    assert client.get(f"{path}/{ident}").status_code == 200

    updated = client.patch(f"{path}/{ident}", json=patch, headers=auth)
    assert updated.status_code == 200
    assert updated.json()["name"] == patch["name"]

    assert client.delete(f"{path}/{ident}", headers=auth).status_code == 204
    assert client.get(f"{path}/{ident}").status_code == 404


@ALL
def test_duplicate_is_a_conflict(client, auth, path, payload, patch, unique):
    client.post(path, json=payload, headers=auth)
    again = client.post(path, json=payload, headers=auth)
    assert again.status_code == (409 if unique else 201)


@ALL
def test_missing_record_is_404(client, path, payload, patch, unique):
    missing = "zz" if path.endswith("languages") else "99999"
    response = client.get(f"{path}/{missing}")
    assert response.status_code == 404
    assert "not found" in response.json()["detail"]


@ALL
def test_list_is_paginated_and_ordered(client, auth, path, payload, patch, unique):
    for index in range(3):
        body = dict(payload)
        body["name"] = f"{payload['name']} {index}"
        if "code" in body:
            body["code"] = ["aa", "bb", "cc"][index]
        assert client.post(path, json=body, headers=auth).status_code == 201

    first = client.get(f"{path}?limit=2").json()
    second = client.get(f"{path}?limit=2&offset=2").json()
    assert len(first) == 2
    assert len(second) == 1

    keys = [identifier(row) for row in first + second]
    assert len(set(keys)) == 3, "pagination repeated a row"
    assert keys == sorted(keys), "results are not ordered by primary key"


@ALL
@pytest.mark.parametrize("limit", [0, -1, 101])
def test_limit_is_bounded(client, path, payload, patch, unique, limit):
    assert client.get(f"{path}?limit={limit}").status_code == 422


@ALL
def test_offset_cannot_be_negative(client, path, payload, patch, unique):
    assert client.get(f"{path}?offset=-1").status_code == 422
