"""Rename fields

Revision ID: 50167f5c4a29
Revises: 60529d5cd368
Create Date: 2026-06-16 21:51:17.504580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50167f5c4a29'
down_revision: Union[str, Sequence[str], None] = '60529d5cd368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_certification_year'), table_name='portfolio_certification')
    op.drop_constraint(op.f('portfolio_certification_validation_serial_key'), 'portfolio_certification', type_='unique')
    op.drop_index(op.f('ix_portfolio_course_year'), table_name='portfolio_course')
    op.add_column('portfolio_project', sa.Column('difficulty_level_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('portfolio_project_difficulty_id_fkey'), 'portfolio_project', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_project', 'portfolio_difficulty_level', ['difficulty_level_id'], ['id'])
    op.drop_column('portfolio_project', 'difficulty_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_project', sa.Column('difficulty_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'portfolio_project', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_project_difficulty_id_fkey'), 'portfolio_project', 'portfolio_difficulty_level', ['difficulty_id'], ['id'])
    op.drop_column('portfolio_project', 'difficulty_level_id')
    op.create_index(op.f('ix_portfolio_course_year'), 'portfolio_course', ['year'], unique=False)
    op.create_unique_constraint(op.f('portfolio_certification_validation_serial_key'), 'portfolio_certification', ['validation_serial'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_portfolio_certification_year'), 'portfolio_certification', ['year'], unique=False)
    # ### end Alembic commands ###
