"""Add commence time colummn

Revision ID: f44c971ab177
Revises: a3bc0fe6b0f8
Create Date: 2026-06-27 14:02:01.676725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f44c971ab177'
down_revision: Union[str, Sequence[str], None] = 'a3bc0fe6b0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statpitch_match_prediction', sa.Column('commence_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statpitch_match_prediction', 'commence_time')
    # ### end Alembic commands ###
